### ISSUE TITLE
What should I be using as the default path for SFTP connection

### ISSUE THREAD

**Issue by connorpiper99** [DarwinBaker/AATool#65]
I have a SFTP server that is setup correctly, and the AATool is able to find something. But it does not recognize any achievements.

I have tried setting the root folder for my SFTP server as both the Minecraft server folder, and then the world folder. Both did not work. 

What should I using for the  path?

![image](https://user-images.githubusercontent.com/126643023/222047501-1ea1f10e-6d43-4330-8c7b-e02da0ce35bf.png)

**Comment by connorpiper99** [comment]
![image](https://user-images.githubusercontent.com/126643023/222048407-ff18da9f-4a2c-4f9c-92df-7f872689431d.png)

**Comment by DarwinBaker** [comment]
I just released a version that should hopefully fix an issue with pathing on some servers, would you mind updating and letting me know if that fixed it? You should be able to just leave the box blank

**Comment by connorpiper99** [comment]
The update did install, but nothing seems to have changed. I never had put anything in that box. I have the root of my SFTP server set to just being the server folder. I will include a screenshot of what the root looks like. 
![image](https://user-images.githubusercontent.com/126643023/222808213-4ab15a59-9b7a-423a-a62e-7813387bd77b.png)

**Comment by connorpiper99** [comment]
EDIT: I am noticing that the auto detect is sometimes detecting 1.16 and sometimes 1.19. It is a 1.19 server. Manually selecting the correct version does not resolve the issue however.

**Comment by DarwinBaker** [comment]
Yeah, based on that screenshot the path should be left blank. Out of curiosity, what happens if you set player filtering to combined instead of solo?

**Comment by connorpiper99** [comment]
Combined makes no difference. I have the server path set blank. I did check to make sure the world was not screwed up, loading it in singleplayer does work with the tool, and it shows all achievements.
