### ISSUE TITLE
SFTP path - wrong slashes

### ISSUE THREAD

**Issue by togoghula** [DarwinBaker/AATool#78]
Hi Darwin,
this is my very first github post. I am not familiar how to post issues. I hope it will be comprehensible.
I am trying AATool 1.6.4 to connect to a SFTP host.
The game server root is down one subdirectory in a chroot sftp-user context with a mount bind to the real location.
Like so: ie /home/user/subdirectory
I can traverse the directory correctly with a sftp-client.
AATool wont find any file, so I switched on SFTP logging.
This is the finding:
'open "/subdirectory\\\\server.properties" flags READ mode 0666'
'sent status No such file'
I think the path should look like "/subdirectory/server.properties"
I may be wrong, but I guess double backslashes are only for windows context.
And yes, the SFTP-host is a linux host.
Thank you and best regards
togoghula

**Comment by DarwinBaker** [comment]
I released an update a while back that fixed linux compatibility by appropriately replacing a backslash with a forward slash, but I must have missed another one related to custom paths. I'll make sure this gets fixed

**Comment by togoghula** [comment]
I've managed to quick fix the code at least for my environment (Win10 <-SFTP-> Ubuntu Jammy).
Now sync is running successfully.
In MinecraftServer.cs I omitted the LinuxMode switch:
```
        public static string HostAwarePath(params string[] paths) =>
             //LinuxMode ? Path.Combine(paths).Replace("\\", "/") : Path.Combine(paths);
             Path.Combine(paths).Replace(@"\", "/");
```
Somehow the commented line was adding double backslashes instead of replacing them.

**Comment by Gills2794** [comment]
I just installed version 1.7.0.0 and seems this issue is still unresolved. I had to quick fix the code same as @togoghula

**Comment by DarwinBaker** [comment]
I've added the option to manually specify if your host is Windows or Linux and fixed the path formatting.
